language: php

php:
  - 5.4
  - 5.5

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit -c ./phpunit.dist.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: martin.aarhof@gmail.com

env:
  global:
    secure: L7HtlaQF2/5EiKobyDb7GYo+ggH2w0hRKDIaKQTVwowb2tJ4Vsp15nu5kaOfI/eMbSFR28ATSSrCZqVTq06bEpwvF/CZbkeEjUdFX/te6lIqirGyglQg2JWI++FaBxJAT+11BL5wnCjpLKpwBTdeB84oP9BCC7u50oMLMTwSk0A=